version: "3.8"

services:
  backend:
    build: .
    container_name: paofacil-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://breadeasy-app.postgres.database.azure.com:5432/breadeasy_db?sslmode=require
      SPRING_DATASOURCE_USERNAME: breadeasy  # Nome de usuário do Azure PostgreSQL
      SPRING_DATASOURCE_PASSWORD: 123456789@Aa  # Senha do usuário do banco de dados
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8082:8080"  # Mapeia a porta 8082 do host para a porta 8080 do container
    networks:
      - paofacil-network

networks:
  paofacil-network:
    driver: bridge  # Tipo de rede para o Docker Compose
