version: "3.8"

services:
  backend:
    build: .
    container_name: paofacil-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://paofacil-server.postgres.database.azure.com:5432/paofacil-database?sslmode=require
      SPRING_DATASOURCE_USERNAME: adminuser
      SPRING_DATASOURCE_PASSWORD: novaSenha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8081:8080"
    networks:
      - paofacil-network

networks:
  paofacil-network:
