name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # Passo 2: Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    # Passo 3: Build com Maven
    - name: Build with Maven
      run: ./mvnw clean install

    # Passo 4: Testar com Maven
    - name: Test with Maven
      run: ./mvnw test
