name: Deploy to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Move to backend directory
      run: cd backend # Comando correto para mudar para o diretório backend
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'paofacil-backend'   # Nome da aplicação no Azure
        slot-name: 'production'        # Nome do slot de produção
        package: '.'                    # O diretório onde o código está localizado
