name: Build and deploy Java app to Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name         # Nome do seu Azure Web App
  JAVA_VERSION: '17'                       # Versão do Java
  DISTRIBUTION: zulu                       # Distribuição do Java (se estiver usando Zulu)
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   # ID da sua assinatura Azure
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}               # ID do Tenant Azure
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}               # ID do Client/Service Principal
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}       # Senha do Service Principal

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Navigate to backend directory (if needed)
        run: cd backend

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/backend/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
