name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Ou a branch que você está usando para deploy, por exemplo, 'deploy-to-azure'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'   # Altere para 11, conforme seu caso

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: ${{ github.workspace }}/target/*.jar  # Caminho para o arquivo JAR gerado

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v2
        with:
          name: app-artifact

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NovoAppWebApp'  # Nome do seu aplicativo no Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Segredo com o perfil de publicação
          package: '*.jar'  # O pacote (arquivo .jar) que será enviado para o Azure
