name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v2

      # Passo 2: Configurar JDK 11 (usando Adoptium)
      - name: Configurar JDK 11 (Adoptium)
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Atualização para o Adoptium (temurin)

      # Passo 3: Rodar testes e build com Maven
      - name: Executar Maven Build
        run: mvn clean install -f backend/pom.xml
