name: Deploy to Azure App Service

on:
  push:
    branches:
      - deploy-to-azure-app-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      # Navega até a pasta backend
      - name: Move to backend directory
        run: cd backend

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Realiza o build da aplicação Spring Boot
      - name: Build Project
        run: mvn clean install -DskipTests  # ou sem -DskipTests se quiser rodar os testes

      # Verifica se o arquivo JAR foi gerado corretamente
      - name: List files in target folder
        run: ls -l backend/target  # Mostra os arquivos gerados no diretório target

      # Envia o artefato gerado para a próxima etapa (deploy)
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: springboot-example
          path: backend/target/*.jar  # Certifique-se que o JAR foi gerado aqui

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: springboot-example

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NovoAppWebApp'  # Nome da aplicação no Azure
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '*.jar'  # Certifique-se de que o arquivo JAR está sendo enviado
