name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - deploy-to-azure-app-service  # Roda quando há push nessa branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Project
        run: mvn clean install -DskipTests
        working-directory: backend

      - name: List files in target folder
        run: ls -l backend/target

      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend-jar
          path: backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend-jar

      - name: Test DNS resolution
        run: nslookup breadeasy-azure-egf7hpaefvb0egg2.canadacentral-01.azurewebsites.net

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'breadeasy-azure-egf7hpaefvb0egg2'  # Nome correto do App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
