name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger o workflow apenas para o branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Usando a imagem mais recente do Ubuntu

    steps:
    # 1. Verificar o repositório
    - name: Check out the repository
      uses: actions/checkout@v2  # Faz checkout do repositório

    # 2. Configurar o Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Configura a ferramenta Buildx para builds multi-plataforma

    # 3. Logar no Docker Hub usando os secrets
    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin  # Realiza o login no Docker Hub de forma segura

    # 4. Construir a imagem Docker
    - name: Build Docker image
      run: |
        docker build -f ./backend/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/your-image-name ./backend  # Construa a imagem com o nome do seu repositório no Docker Hub

    # 5. Enviar a imagem para o Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name  # Envia a imagem para o Docker Hub
