name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest  # O ambiente em que o GitHub Actions rodará o job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Versão mais recente do actions/checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Versão mais recente do setup-buildx

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verifica se o docker-compose foi instalado corretamente

      - name: Cache Docker layers
        uses: actions/cache@v3  # Versão mais recente do actions/cache
        with:
          path: /tmp/.buildx-cache  # Caminho do cache Docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t paofacil-backend ./backend  # Faz o build da imagem do backend

      - name: Run Docker Compose (se necessário)
        run: |
          docker-compose -f ./backend/docker-compose.yml up -d  # Caminho correto para o docker-compose.yml no diretório backend

      - name: Test Docker container
        run: |
          docker ps  # Verifica se o container está em execução

      - name: Push Docker image to Docker Hub (opcional)
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag paofacil-backend ${{ secrets.DOCKER_USERNAME }}/paofacil-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/paofacil-backend:latest  # Faz o push da imagem para o Docker Hub (se necessário)

      - name: Deploy Backend (opcional)
        run: |
          ssh user@server 'docker pull ${{ secrets.DOCKER_USERNAME }}/paofacil-backend:latest && docker run -d ${{ secrets.DOCKER_USERNAME }}/paofacil-backend:latest'
