name: Deploy React to Surge

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout o código
      - name: Checkout the code
        uses: actions/checkout@v4

      # 2. Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          cd painel-dashboard
          npm install

      # 4. Build do projeto
      - name: Build the project
        run: |
          cd painel-dashboard
          npm run build

      # 5. Instalar o Surge
      - name: Install Surge
        run: npm install --global surge

      # 6. Deploy para o Surge
      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # Usando o secret SURGE_TOKEN
        run: |
          cd painel-dashboard/build
          surge . pao-facil.surge.sh --token $SURGE_TOKEN
