name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # Passo 2: Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    # Passo 3: Entrar no diretório do backend
    - name: Navigate to backend directory
      run: cd backend

    # Passo 4: Cache Maven dependencies (se necessário)
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: backend/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('backend/**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Passo 5: Build com Maven no diretório backend
    - name: Build with Maven
      run: cd backend && ./mvnw clean install

    # Passo 6: Testar com Maven no diretório backend
    - name: Test with Maven
      run: cd backend && ./mvnw test
